services:
  db:
    image: pgvector/pgvector:pg14
    container_name: rag_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: rag_redis
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rag_api
    ports:
      - "8000:8000"
    env_file: .env 
    volumes:
      - ./api/srcp:/app/api/srcp
      - ./src:/app/src
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: rag_worker
    command: celery -A src.workers.celery_app worker --loglevel=info
    env_file: .env 
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./processed:/app/processed
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  pg_data: