services:
  db:
    image: pgvector/pgvector:pg14
    container_name: rag_postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ragdb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"

  # worker:
  #   build: .
  #   container_name: rag_worker
  #   commandd : celery -A src.workers.celery_app worker --loglevel=info   
  #   environment:
  #     - DB_URL=${DB_URL}
  #     - REDIS_URL=${REDIS_URL}
  #   depends_on:
  #     - db
  #     - redis

volumes:
  pg_data: