services:
  db:
    image: pgvector/pgvector:pg14
    container_name: rag_postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ragdb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./api/srcp:/app/api/srcp  
      - ./src:/app/src          
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: src/Dockerfile 
    container_name: rag_worker
    command: celery -A src.workers.celery_app worker --loglevel=info
    environment:
      - DB_URL="postgresql+psycopg2://myuser:mypassword@127.0.0.1:5433/ragdb"
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src:/app             # Map toàn bộ thư mục src vào /app trong container
      - ./data:/app/data
      - ./processed:/app/processed
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  pg_data: