"""Revert FTS changes and remove content_tsv column

Revision ID: 07d53b483c11
Revises: a485160cd445
Create Date: 2025-10-02 16:10:42.235858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d53b483c11'
down_revision: Union[str, Sequence[str], None] = 'a485160cd445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_content_tsv'), table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'content_tsv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_chunks_content_tsv'), 'chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
