"""Updated media_id for SourceDocument

Revision ID: 0ce80e27632c
Revises: a6ff499bd8a8
Create Date: 2025-09-19 11:29:50.464334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce80e27632c'
down_revision: Union[str, Sequence[str], None] = 'a6ff499bd8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('media_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_column('source_documents', 'media_id')
    # ### end Alembic commands ###
