"""Added cascade for auto deletion based on admin id

Revision ID: 2c07ebc92fa0
Revises: f0da8b83855f
Create Date: 2025-09-19 11:48:57.876327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c07ebc92fa0'
down_revision: Union[str, Sequence[str], None] = 'f0da8b83855f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
