"""Add tsvector column for full-text search

Revision ID: a485160cd445
Revises: 13eef78ca794
Create Date: 2025-10-02 15:17:54.058059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a485160cd445'
down_revision: Union[str, Sequence[str], None] = '13eef78ca794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True))
    op.drop_index(op.f('ix_chunks_embedding'), table_name='chunks', postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.create_index('ix_chunks_content_tsv', 'chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_content_tsv', table_name='chunks', postgresql_using='gin')
    op.create_index(op.f('ix_chunks_embedding'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.drop_column('chunks', 'content_tsv')
    # ### end Alembic commands ###
