"""Updated media_id for SourceDocument

Revision ID: f0da8b83855f
Revises: 0ce80e27632c
Create Date: 2025-09-19 11:42:14.118883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0da8b83855f'
down_revision: Union[str, Sequence[str], None] = '0ce80e27632c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.create_index(op.f('ix_source_documents_media_id'), 'source_documents', ['media_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_documents_media_id'), table_name='source_documents')
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=True)
    # ### end Alembic commands ###
